export default{
    menuList:[
        {
          title:"收藏列表",
          icon:"collect.png",
          navigate:"/pages/collect/main"
        },
        {
          title:"发布公告",
          icon:"history.png",
          navigate:"/pages/history/main"
        },
        {
          title:"邀请好友",
          icon:"invitation.png",
          navigate:"/pages/invitation/main"
        },
        {
          title:"产品意见",
          icon:"advice.png",
          navigate:"/pages/advice/main"
        },
        {
            title:"新添加",
            icon:"invitation.png"
        }
      ]
}